### ISSUE TITLE
Add support for ESXi Hosts in non-cluster vSphere environments

### ISSUE THREAD

**Issue by mhmdio** [vmware-samples/packer-examples-for-vsphere#458]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Description

In some environments, there is no cluster between hosts, so I suggest supporting Hosts, instead of passing a cluster

### Use Case(s)

for example, if you have a home lab with 1 vcenter and 1 esxi.

### Potential Configuration

I have tested the following with `vCenter 8.0` and `vSphere ESXi 8.0` and `Packer 1.8.5`
```hcl
source "vsphere-iso" "linux-rocky" {
...
  cluster   = var.cluster_enabled ? var.vsphere_cluster : null
  host       = var.cluster_enabled ? null : var.vsphere_host
...
}
```

### References

https://developer.hashicorp.com/packer/plugins/builders/vsphere/vsphere-iso#working-with-clusters-and-hosts

**Comment by tenthirtyam** [comment]
Hi @mhmdio - please feel free to submit a pull request for contribution after reviewing the guidelines `CONTRIBUTING.md`.

**Comment by tintinhamans** [comment]
AFAIK, there is no need to do anything complex to make this work since Packer is perfectly happy receiving an empty string for the "vsphere_cluster" value as well as for the "vsphere_folder" value. The latter needs to be empty when targetting standalone ESXi hosts (without vCenter) as they do not support folders.


Below has been tested working on a standalone ESXi host for me: 

*Snippet of /config/vsphere.pkrvars.hcl*
 ```
...
 // vSphere Settings
vsphere_datacenter = "ha-datacenter"
vsphere_cluster    = ""
vsphere_host       = "%hostname%"
vsphere_datastore  = "%datastore%"
vsphere_network    = "%network%"
vsphere_folder     = ""
```
*Snippet of /builds/%os%variables.pkr.hcl*

```
...
variable "vsphere_host" {
  type        = string
  description = "The name of the target vSphere host. (e.g. 'sfo01-w01-esx01')"
}
...
```
*Snippet of /builds/%os%/%os%.pkr.hcl*
```
...
source "vsphere-iso" "%os%" {
  ...
  host       = var.vsphere_host
  ...
}
...
  post-processor "manifest" {
    ...
    custom_data = {
      ...
      vsphere_host             = var.vsphere_host
      ...
    }
  }
...
```
